name: Checkout app CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        
#       - name: Setup Java JDK
#         uses: actions/setup-java@v3
#         with:
#           java-version: 1.8
#           distribution: 'adopt'
      
      - name: Gradle wrapper
        run: gradle wrapper
      
      - name: Gradle test
        run: ./gradlew test
        
      - name: Gradle build
        run: ./gradlew build
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Checkout Calculator
          path: app/build/outputs/apk/debug/app-debug.apk
