name: Checkout app CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      
      - name: Run Gradle wrapper
        run: gradle wrapper
        
      - name: Build with gradle
        run: ./gradlew build
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Checkout Calculator
          path: app/build/outputs/apk/debug/app-debug.apk
